function [fitresult, gof] = createLinearFit(tim, serie)
%CREATEFIT(TIM,HOLA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: tim
%      Y Output: hola
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Apr-2023 13:19:01


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( tim, serie );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Linear fit' );
h = plot( fitresult, xData, yData );
legend( h, 'Data vs. Time', 'Linear fit ', 'Location', 'NorthWest', 'Interpreter', 'latex' );
% Label axes
xlabel( 'Time [min]', 'Interpreter', 'none' );
ylabel( 'Data [g]', 'Interpreter', 'none' );
grid on


